/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/classrooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Classrooms
         * @description Returns list of classrooms joined with their current live state (§7.2).
         */
        get: operations["list_classrooms_api_classrooms_get"];
        put?: never;
        /**
         * Create Classroom
         * @description Creates a new classroom and provisions default classroom_state.
         */
        post: operations["create_classroom_api_classrooms_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/classrooms/{classroom_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Classroom Detail
         * @description Returns detailed room status: state + active & next timetable entry + open alerts (§7.2).
         */
        get: operations["get_classroom_detail_api_classrooms__classroom_id__get"];
        /** Update Classroom */
        put: operations["update_classroom_api_classrooms__classroom_id__put"];
        post?: never;
        /** Delete Classroom */
        delete: operations["delete_classroom_api_classrooms__classroom_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/classrooms/{classroom_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Classroom History
         * @description Returns snapshot history series for occupancy, temperature, and appliance status.
         */
        get: operations["get_classroom_history_api_classrooms__classroom_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/timetable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Timetable */
        get: operations["get_timetable_api_timetable_get"];
        put?: never;
        /** Create Timetable Entry */
        post: operations["create_timetable_entry_api_timetable_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/timetable/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Timetable Entry */
        put: operations["update_timetable_entry_api_timetable__entry_id__put"];
        post?: never;
        /** Delete Timetable Entry */
        delete: operations["delete_timetable_entry_api_timetable__entry_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["get_settings_api_settings_get"];
        /** Update Settings */
        put: operations["update_settings_api_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/preset/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Switch Preset */
        post: operations["switch_preset_api_settings_preset__name__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sensor-data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest Sensor Data
         * @description Ingests raw sensor telemetry from either the sensor-sim or physical ESP32 (§7.1).
         *     Protected by X-Device-Key header.
         */
        post: operations["ingest_sensor_data_api_sensor_data_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/classrooms/{classroom_id}/commands/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Pending Commands
         * @description Returns queued appliance commands awaiting execution by device (§7.1).
         */
        get: operations["get_pending_commands_api_classrooms__classroom_id__commands_pending_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/commands/{command_id}/ack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Acknowledge Command
         * @description Acknowledges appliance command execution by device (§7.1).
         */
        post: operations["acknowledge_command_api_commands__command_id__ack_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AckResponse */
        AckResponse: {
            /**
             * Acked
             * @default true
             */
            acked: boolean;
        };
        /** ClassroomCreate */
        ClassroomCreate: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Building */
            building: string;
            /**
             * Floor
             * @default 1
             */
            floor: number;
            /**
             * Capacity
             * @default 40
             */
            capacity: number;
            /**
             * Room Type
             * @default lecture
             */
            room_type: string;
            /**
             * Has Camera
             * @default false
             */
            has_camera: boolean;
            /**
             * Has Pir
             * @default true
             */
            has_pir: boolean;
            /**
             * Has Dht
             * @default true
             */
            has_dht: boolean;
            /**
             * Ac Rated Kw
             * @default 1.5
             */
            ac_rated_kw: number;
            /**
             * Lights Rated Kw
             * @default 0.3
             */
            lights_rated_kw: number;
            /**
             * Active
             * @default true
             */
            active: boolean;
        };
        /** ClassroomResponse */
        ClassroomResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Building */
            building: string;
            /**
             * Floor
             * @default 1
             */
            floor: number;
            /**
             * Capacity
             * @default 40
             */
            capacity: number;
            /**
             * Room Type
             * @default lecture
             */
            room_type: string;
            /**
             * Has Camera
             * @default false
             */
            has_camera: boolean;
            /**
             * Has Pir
             * @default true
             */
            has_pir: boolean;
            /**
             * Has Dht
             * @default true
             */
            has_dht: boolean;
            /**
             * Ac Rated Kw
             * @default 1.5
             */
            ac_rated_kw: number;
            /**
             * Lights Rated Kw
             * @default 0.3
             */
            lights_rated_kw: number;
            /**
             * Active
             * @default true
             */
            active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ClassroomStateResponse */
        ClassroomStateResponse: {
            /** Classroom Id */
            classroom_id: string;
            /** Occupancy State */
            occupancy_state: string;
            /** Confidence Level */
            confidence_level: string;
            /** Reasons */
            reasons: string[];
            /** People Count */
            people_count?: number | null;
            /** Expected Occupancy */
            expected_occupancy: boolean;
            /** Timetable Entry Id */
            timetable_entry_id?: number | null;
            /** Last Camera At */
            last_camera_at?: string | null;
            /** Last Camera Count */
            last_camera_count?: number | null;
            /** Last Sensor At */
            last_sensor_at?: string | null;
            /** Last Motion At */
            last_motion_at?: string | null;
            /** Last Presence At */
            last_presence_at?: string | null;
            /** Idle Minutes */
            idle_minutes: number;
            /** Temperature */
            temperature?: number | null;
            /** Humidity */
            humidity?: number | null;
            /** Ac Status */
            ac_status: boolean;
            /** Light Status */
            light_status: boolean;
            /** Camera Online */
            camera_online: boolean;
            /** Sensor Online */
            sensor_online: boolean;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ClassroomUpdate */
        ClassroomUpdate: {
            /** Name */
            name?: string | null;
            /** Building */
            building?: string | null;
            /** Floor */
            floor?: number | null;
            /** Capacity */
            capacity?: number | null;
            /** Room Type */
            room_type?: string | null;
            /** Has Camera */
            has_camera?: boolean | null;
            /** Has Pir */
            has_pir?: boolean | null;
            /** Has Dht */
            has_dht?: boolean | null;
            /** Ac Rated Kw */
            ac_rated_kw?: number | null;
            /** Lights Rated Kw */
            lights_rated_kw?: number | null;
            /** Active */
            active?: boolean | null;
        };
        /** ClassroomWithStateResponse */
        ClassroomWithStateResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Building */
            building: string;
            /**
             * Floor
             * @default 1
             */
            floor: number;
            /**
             * Capacity
             * @default 40
             */
            capacity: number;
            /**
             * Room Type
             * @default lecture
             */
            room_type: string;
            /**
             * Has Camera
             * @default false
             */
            has_camera: boolean;
            /**
             * Has Pir
             * @default true
             */
            has_pir: boolean;
            /**
             * Has Dht
             * @default true
             */
            has_dht: boolean;
            /**
             * Ac Rated Kw
             * @default 1.5
             */
            ac_rated_kw: number;
            /**
             * Lights Rated Kw
             * @default 0.3
             */
            lights_rated_kw: number;
            /**
             * Active
             * @default true
             */
            active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            state?: components["schemas"]["ClassroomStateResponse"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PendingCommandResponse */
        PendingCommandResponse: {
            /** Id */
            id: number;
            /** Classroom Id */
            classroom_id: string;
            /** Device */
            device: string;
            /** Command */
            command: string;
        };
        /** SensorEventSchema */
        SensorEventSchema: {
            /** Classroom Id */
            classroom_id: string;
            /** Device Id */
            device_id?: string | null;
            /**
             * Pir Motion
             * @default false
             */
            pir_motion: boolean;
            /** Event */
            event?: string | null;
            /** Temperature */
            temperature?: number | null;
            /** Humidity */
            humidity?: number | null;
            /**
             * Ac Status
             * @default false
             */
            ac_status: boolean;
            /**
             * Light Status
             * @default false
             */
            light_status: boolean;
            /** Wifi Rssi */
            wifi_rssi?: number | null;
            /**
             * Source
             * @default simulation
             * @enum {string}
             */
            source: "simulation" | "esp32";
            /** Timestamp */
            timestamp?: string | null;
        };
        /** SettingsResponse */
        SettingsResponse: {
            /** Preset */
            preset: string;
            /** Values */
            values: {
                [key: string]: unknown;
            };
        };
        /** SettingsUpdate */
        SettingsUpdate: {
            /** Preset */
            preset?: ("production" | "demo") | null;
            /**
             * Values
             * @default {}
             */
            values: {
                [key: string]: unknown;
            };
        };
        /** TimetableEntryCreate */
        TimetableEntryCreate: {
            /** Classroom Id */
            classroom_id: string;
            /** Subject */
            subject: string;
            /** Faculty */
            faculty: string;
            /** Day Of Week */
            day_of_week: number;
            /**
             * Start Time
             * Format: time
             */
            start_time: string;
            /**
             * End Time
             * Format: time
             */
            end_time: string;
            /**
             * Class Type
             * @default lecture
             */
            class_type: string;
            /** Valid From */
            valid_from?: string | null;
            /** Valid To */
            valid_to?: string | null;
        };
        /** TimetableEntryResponse */
        TimetableEntryResponse: {
            /** Classroom Id */
            classroom_id: string;
            /** Subject */
            subject: string;
            /** Faculty */
            faculty: string;
            /** Day Of Week */
            day_of_week: number;
            /**
             * Start Time
             * Format: time
             */
            start_time: string;
            /**
             * End Time
             * Format: time
             */
            end_time: string;
            /**
             * Class Type
             * @default lecture
             */
            class_type: string;
            /** Valid From */
            valid_from?: string | null;
            /** Valid To */
            valid_to?: string | null;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** TimetableEntryUpdate */
        TimetableEntryUpdate: {
            /** Subject */
            subject?: string | null;
            /** Faculty */
            faculty?: string | null;
            /** Day Of Week */
            day_of_week?: number | null;
            /** Start Time */
            start_time?: string | null;
            /** End Time */
            end_time?: string | null;
            /** Class Type */
            class_type?: string | null;
            /** Valid From */
            valid_from?: string | null;
            /** Valid To */
            valid_to?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_classrooms_api_classrooms_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassroomWithStateResponse"][];
                };
            };
        };
    };
    create_classroom_api_classrooms_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClassroomCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassroomResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_classroom_detail_api_classrooms__classroom_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                classroom_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_classroom_api_classrooms__classroom_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                classroom_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClassroomUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassroomResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_classroom_api_classrooms__classroom_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                classroom_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_classroom_history_api_classrooms__classroom_id__history_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                resolution?: string;
            };
            header?: never;
            path: {
                classroom_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_timetable_api_timetable_get: {
        parameters: {
            query?: {
                classroom_id?: string | null;
                day?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimetableEntryResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_timetable_entry_api_timetable_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TimetableEntryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimetableEntryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_timetable_entry_api_timetable__entry_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TimetableEntryUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimetableEntryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_timetable_entry_api_timetable__entry_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
        };
    };
    update_settings_api_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    switch_preset_api_settings_preset__name__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_sensor_data_api_sensor_data_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Device-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SensorEventSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pending_commands_api_classrooms__classroom_id__commands_pending_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Device-Key"?: string;
            };
            path: {
                classroom_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingCommandResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    acknowledge_command_api_commands__command_id__ack_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Device-Key"?: string;
            };
            path: {
                command_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AckResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
