"""initial_classroom_schema

Revision ID: d93313395e38
Revises: 
Create Date: 2026-09-29 01:06:30.927752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd93313395e38'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('classroom_id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('headline', sa.String(length=256), nullable=False),
    sa.Column('detail', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alerts_room_type_status', 'alerts', ['classroom_id', 'type', 'status'], unique=False)
    op.create_index('idx_alerts_status', 'alerts', ['status'], unique=False)
    op.create_table('camera_detections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('classroom_id', sa.String(length=32), nullable=False),
    sa.Column('camera_id', sa.String(length=64), nullable=False),
    sa.Column('people_detected', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('device_timestamp', sa.DateTime(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_camera_room_received', 'camera_detections', ['classroom_id', 'received_at'], unique=False)
    op.create_table('classrooms',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('building', sa.String(length=64), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('room_type', sa.String(length=32), nullable=False),
    sa.Column('has_camera', sa.Boolean(), nullable=False),
    sa.Column('has_pir', sa.Boolean(), nullable=False),
    sa.Column('has_dht', sa.Boolean(), nullable=False),
    sa.Column('ac_rated_kw', sa.Float(), nullable=False),
    sa.Column('lights_rated_kw', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_commands',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('classroom_id', sa.String(length=32), nullable=False),
    sa.Column('device', sa.String(length=16), nullable=False),
    sa.Column('command', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('requested_by', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('acked_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_commands_room_status', 'device_commands', ['classroom_id', 'status'], unique=False)
    op.create_table('occupancy_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('classroom_id', sa.String(length=32), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('occupancy_state', sa.String(length=32), nullable=False),
    sa.Column('people_count', sa.Integer(), nullable=True),
    sa.Column('expected_occupancy', sa.Boolean(), nullable=False),
    sa.Column('pir_active', sa.Boolean(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('ac_on', sa.Boolean(), nullable=False),
    sa.Column('light_on', sa.Boolean(), nullable=False),
    sa.Column('idle_minutes', sa.Integer(), nullable=False),
    sa.Column('data_source', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_snapshot_room_ts', 'occupancy_snapshots', ['classroom_id', 'ts'], unique=False)
    op.create_table('prediction_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trained_at', sa.DateTime(), nullable=False),
    sa.Column('algorithm', sa.String(length=64), nullable=False),
    sa.Column('n_rows', sa.Integer(), nullable=False),
    sa.Column('synthetic_fraction', sa.Float(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('feature_importance', sa.JSON(), nullable=False),
    sa.Column('artifact_path', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor_readings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('classroom_id', sa.String(length=32), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.Column('pir_motion', sa.Boolean(), nullable=False),
    sa.Column('event', sa.String(length=32), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('ac_status', sa.Boolean(), nullable=False),
    sa.Column('light_status', sa.Boolean(), nullable=False),
    sa.Column('wifi_rssi', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('device_timestamp', sa.DateTime(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sensor_room_received', 'sensor_readings', ['classroom_id', 'received_at'], unique=False)
    op.create_table('settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('preset', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('classroom_state',
    sa.Column('classroom_id', sa.String(length=32), nullable=False),
    sa.Column('occupancy_state', sa.String(length=32), nullable=False),
    sa.Column('confidence_level', sa.String(length=16), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('people_count', sa.Integer(), nullable=True),
    sa.Column('expected_occupancy', sa.Boolean(), nullable=False),
    sa.Column('timetable_entry_id', sa.Integer(), nullable=True),
    sa.Column('last_camera_at', sa.DateTime(), nullable=True),
    sa.Column('last_camera_count', sa.Integer(), nullable=True),
    sa.Column('last_sensor_at', sa.DateTime(), nullable=True),
    sa.Column('last_motion_at', sa.DateTime(), nullable=True),
    sa.Column('last_presence_at', sa.DateTime(), nullable=True),
    sa.Column('idle_minutes', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('ac_status', sa.Boolean(), nullable=False),
    sa.Column('light_status', sa.Boolean(), nullable=False),
    sa.Column('camera_online', sa.Boolean(), nullable=False),
    sa.Column('sensor_online', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('classroom_id')
    )
    op.create_table('timetable_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('classroom_id', sa.String(length=32), nullable=False),
    sa.Column('subject', sa.String(length=128), nullable=False),
    sa.Column('faculty', sa.String(length=128), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('class_type', sa.String(length=32), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_timetable_room_day', 'timetable_entries', ['classroom_id', 'day_of_week'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_timetable_room_day', table_name='timetable_entries')
    op.drop_table('timetable_entries')
    op.drop_table('classroom_state')
    op.drop_table('settings')
    op.drop_index('idx_sensor_room_received', table_name='sensor_readings')
    op.drop_table('sensor_readings')
    op.drop_table('prediction_models')
    op.drop_index('idx_snapshot_room_ts', table_name='occupancy_snapshots')
    op.drop_table('occupancy_snapshots')
    op.drop_index('idx_commands_room_status', table_name='device_commands')
    op.drop_table('device_commands')
    op.drop_table('classrooms')
    op.drop_index('idx_camera_room_received', table_name='camera_detections')
    op.drop_table('camera_detections')
    op.drop_index('idx_alerts_status', table_name='alerts')
    op.drop_index('idx_alerts_room_type_status', table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
